### ISSUE TITLE
Extract vision-only embedding (no language)

### ISSUE THREAD

**Issue by seann999** [siddk/voltron-robotics#15]
I need a function that, given only a preprocessed image (224x224 normalized with ImageNet values), returns its embedding. Is this the correct way to do this? I ask because I'm getting weird behavior with my robot (other embeddings work fine).
```
vcond, _ = load("v-cond-base", device="cuda", freeze=True)
vector_extractor = instantiate_extractor(vcond)().cuda()

def extractor(image):
    visual_embeddings = vcond(image, mode="visual")
    representation = vector_extractor(visual_embeddings)
    return representation

return extractor
```

The embedding is used as input to a small MLP trained with behavior cloning. The MLP seems to underfit (loss is relatively high) with Voltron.

**Comment by siddk** [comment]
So one thing to note is that the `vector_extractor` is actually a randomly initialized "shallow" attention block; you'll need to make sure you're finetuning it along with the rest of the MLP for your BC policy (`v_cond` can remain frozen, but you need to add the vector extractor to the set of parameters for optimization).

Let me know if this makes sense -- happy to drop a more detailed code example if that'd be helpful! If you don't want to try finetuning the vector extractor, and just want to see if Voltron embeddings have signal, you can also just try `representation = visual_embeddings.mean(dim=-1)`.

**Comment by seann999** [comment]
I get a vector of dim 196 with `.mean(dim=-1)`. Did you mean `.mean(dim=1)`, because that averages across the patches? That gets me a 768-D vector.

**Comment by siddk** [comment]
Yes! Sorry that's my bad (off by one)
